//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWinBackGrnd.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestWinBackGrnd.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!-- Created with Inkscape (http://www.inkscape.org/) --&gt;
        ///
        ///&lt;svg
        ///   xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;
        ///   xmlns:cc=&quot;http://creativecommons.org/ns#&quot;
        ///   xmlns:rdf=&quot;http://www.w3.org/1999/02/22-rdf-syntax-ns#&quot;
        ///   xmlns:svg=&quot;http://www.w3.org/2000/svg&quot;
        ///   xmlns=&quot;http://www.w3.org/2000/svg&quot;
        ///   xmlns:sodipodi=&quot;http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd&quot;
        ///   xmlns:inkscape=&quot;http://www.inkscape.org/namespaces/inkscape&quot;
        ///   width=&quot;75pc&quot;
        ///   height=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string self_destruct_warning {
            get {
                return ResourceManager.GetString("self_destruct_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VER 0.1;
        ///
        /////This is a early placeholder for the zastromo underlay drawing system.
        ///
        /////Data
        /////Octagon shape
        ///arr octPoints : {
        ///point(37.5rp, 87.5rp),
        ///point(62.5rp, 87.5rp),
        ///point(87.5rp, 62.5rp),
        ///point(87.5rp, 37.5rp),
        ///point(62.5rp, 12.5rp),
        ///point(37.5rp, 12.5rp),
        ///point(12.5rp, 37.5rp),
        ///point(12.5rp, 62.5rp)
        ///};
        ///
        /////Cross line 1
        ///line line1 : line(
        ///linesplt(octPoints[0], octPoints[7]),
        ///linesplt(octPoints[3], octPoints[4])
        ///);
        /////Cross line 2
        ///line line2 : line(
        ///linesplt(octPoints[1], octPoint [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string zastromo_warning_underlay {
            get {
                return ResourceManager.GetString("zastromo_warning_underlay", resourceCulture);
            }
        }
    }
}
